In [9]:
import torch

In [10]:
x = torch.rand(3, 3)

In [11]:
y = x.view(-1, 3)

In [12]:
x

tensor([[0.7790, 0.5807, 0.0262],
        [0.4691, 0.9370, 0.2537],
        [0.1759, 0.1755, 0.0484]])

In [13]:
b = x.numpy()

In [14]:
b

array([[0.7789629 , 0.5807374 , 0.02619636],
       [0.46911454, 0.9370335 , 0.2536919 ],
       [0.17591041, 0.17554283, 0.04839861]], dtype=float32)

In [15]:
print(b)

[[0.7789629  0.5807374  0.02619636]
 [0.46911454 0.9370335  0.2536919 ]
 [0.17591041 0.17554283 0.04839861]]


In [16]:
print(torch.cuda.is_available())

False
